#!/usr/bin/env python3
"""Generate the project-self-contained Erdos 625 Lean checkpoint.

The output contains the complete transitive closure of the local modules
imported by Erdos625.lean.  Local imports are replaced by source text in
dependency order; external imports remain at the top of the generated file.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parents[1]
ROOT_MODULE = "Erdos625"
ROOT_SOURCE = PROJECT_DIR / "Erdos625.lean"
MODULE_DIR = PROJECT_DIR / "Erdos625"
OUTPUT = PROJECT_DIR / "Erdos625SelfContained.lean"
IMPORT_RE = re.compile(r"^\s*import\s+(.+?)\s*$")


def normalized_text(path: Path) -> str:
    """Read UTF-8 source and normalize line endings for reproducible output."""
    return path.read_text(encoding="utf-8-sig").replace("\r\n", "\n").replace("\r", "\n")


def module_sources() -> dict[str, Path]:
    sources = {ROOT_MODULE: ROOT_SOURCE}
    for path in sorted(MODULE_DIR.rglob("*.lean")):
        relative = path.relative_to(PROJECT_DIR).with_suffix("")
        sources[".".join(relative.parts)] = path
    return sources


def imports_in(text: str, path: Path) -> list[str]:
    imports: list[str] = []
    for line_number, line in enumerate(text.splitlines(), start=1):
        match = IMPORT_RE.match(line)
        if match is None:
            continue
        command = match.group(1).split("--", maxsplit=1)[0].strip()
        names = command.split()
        if not names:
            raise ValueError(f"empty import command at {path}:{line_number}")
        imports.extend(names)
    return imports


def body_without_imports(text: str) -> str:
    lines = [line for line in text.splitlines() if IMPORT_RE.match(line) is None]
    return "\n".join(lines).strip("\n")


def closure_in_dependency_order(
    sources: dict[str, Path],
) -> tuple[list[str], list[str], dict[str, str]]:
    texts = {module: normalized_text(path) for module, path in sources.items()}
    dependencies = {
        module: imports_in(text, sources[module]) for module, text in texts.items()
    }
    ordered: list[str] = []
    external: set[str] = set()
    permanent: set[str] = set()
    temporary: list[str] = []

    def visit(module: str) -> None:
        if module in permanent:
            return
        if module in temporary:
            cycle = " -> ".join([*temporary, module])
            raise ValueError(f"cyclic local import graph: {cycle}")
        if module not in sources:
            raise ValueError(f"missing source for local module {module}")

        temporary.append(module)
        for dependency in dependencies[module]:
            if dependency == ROOT_MODULE or dependency.startswith(f"{ROOT_MODULE}."):
                visit(dependency)
            else:
                external.add(dependency)
        temporary.pop()
        permanent.add(module)
        ordered.append(module)

    visit(ROOT_MODULE)
    return ordered, sorted(external), texts


def section_name(module: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_]", "_", module)
    return f"Erdos625SelfContained_Module_{safe}"


def render() -> tuple[str, list[str], list[str]]:
    sources = module_sources()
    ordered, external, texts = closure_in_dependency_order(sources)

    header = """\
/-!
# Erdos 625: project-self-contained Lean checkpoint

DO NOT EDIT THIS FILE DIRECTLY.
Regenerate it with scripts/generate_self_contained.py.

## Honest status

This is the complete, kernel-checkable source closure of the current partial
formalization.  It is self-contained with respect to this repository:
it imports no Erdos625 project module and instead includes every declaration in
dependency order.  Its only imports are from the Mathlib version pinned by this
project's lake-manifest.json and lean-toolchain.

This file is NOT a complete formal proof of Erdos Problem 625.  In particular,
the remaining Section VIII event-nonemptiness, manuscript-specific
parameterization, and quantitative canonical-event/skeleton estimates; the
Section IX uniform large- and small-residual attachment estimate,
second-moment assembly, and the concrete seed/count/moment estimate and `Lambda`
asymptotics needed to instantiate the proved uniform Lemma 10.2; the concrete
chromatic at-most tail and root separation; and the final probabilistic
theorem are open.  The physical faithful cut of one eligible cycle, its
canonical source-free encoder, decoder left inverse, injectivity, exact
weight, dependent marked packaging, exact endpoint enumeration, and aggregate
mixed-cycle-to-nested-walk domination are included and proved.  The abstract
geometric sum with exactly one `2 * |M|` cost and its deterministic literal-
`residualQ` specialization under an explicit strict-regime premise are also
included and proved.  The canonical positive support is proved matching under
the ambient caps; the two local reward presentations agree exactly; one fixed
family's local factors are separated; their finite even-family sum is bounded
by the simple-cycle polymer product; this sum is identified exactly with the
event-restricted actual-attachment numerator and the polymer bound is transferred
to it; and the cycle sum is partitioned exactly into mixed and residual-only
terms.  The residual-only term is bounded by an exact row-rooted even-walk
enumeration under finite row/column kernel bounds.  Manuscript (9.1) already
retains the cap/no-return indicator, so no division by its event mass is
required.  The pointwise cubic `residualLambda` bound and its deterministic
total estimate at the scale in (9.13) are included and proved.  The canonical
full/residual reward-product and support-graph splits are included and proved,
with no-return and `2 ≤ U` explicit in their respective hypotheses.  The
literal actual even family is exactly transported to the bipartite binary
cycle space, and the event-restricted attachment numerator is exactly rewritten
by its finite cycle-rank factor.  For each attained canonical-demand fibre,
the tagged uniform-law attachment sum is exactly the labelled-witness incidence
times that numerator, and this identity is now summed exactly over the full
dependent demand/witness/residual sigma space.  This global finite assembly
still proves no uniform attachment estimate.
The D1 graph-specific chromatic-tail adapter, D2 two-tail threshold assembly,
D4 count-to-cocolourable Paley--Zygmund seed adapter, and D3 uniform seed/root
wrapper are included and proved as conditional implications.  They retain the
concrete chromatic at-most tail, concrete seed/count/moment estimate with
`Lambda` asymptotics, and concrete root separation as explicit inputs; none of
those inputs is proved by the adapters.
The generic signed-slope root-separation lemma, exact midpoint floor/ceiling
rounding lemma (and explicit natural-index adapter), negligible explicit
rounding budget, and their exact-constant corridor adapter are included. They
remain conditional/deterministic: they do not construct the manuscript roots,
establish their signed advantage or derivative ceiling, or prove the concrete
chromatic tail.
The exact four-deficit score convergence and compatible-Boolean-sign component
count are included as finite helper leaves only.  They do not prove the
four-size signed first moment, the sign-summed second-moment law, the concrete
chromatic tail, the Section IX seed/count/moment estimate or its `Lambda`
asymptotics, the root separation, or `Erdos625Statement`.
The physical unlabelled-skeleton fibre grouping is also included: it groups
finite type-table weights over attained fibres and performs both the
one-factorial fibre rewrite and the exact characteristic-zero quotient form
with a single cell-factorial denominator.  It does not prove a skeleton
probability estimate, the Section IX seed or `Lambda` asymptotic, or
`Erdos625Statement`.
The final target proposition `Erdos625Statement` remains deliberately
unproved.  The included #print axioms commands audit the central declarations
that have actually been proved.

Generated deterministically from Erdos625.lean and its transitive local import
closure.  Each source boundary records the normalized source SHA-256.
-/
"""

    # Lean requires every import command to precede all ordinary commands,
    # including a module documentation comment.
    chunks = [*(f"import {module}" for module in external), "", header.rstrip(), ""]

    for module in ordered:
        path = sources[module]
        relative = path.relative_to(PROJECT_DIR).as_posix()
        text = texts[module]
        digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
        section = section_name(module)
        body = body_without_imports(text)
        chunks.extend(
            [
                "/- " + "=" * 74,
                f"BEGIN SOURCE MODULE: {module}",
                f"Source: {relative}",
                f"Normalized SHA-256: {digest}",
                "=" * 74 + " -/",
                f"section {section}",
                "",
                body,
                "",
                f"end {section}",
                "/- " + "=" * 74,
                f"END SOURCE MODULE: {module}",
                "=" * 74 + " -/",
                "",
            ]
        )

    rendered = "\n".join(chunks).rstrip() + "\n"
    return rendered, ordered, external


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail unless Erdos625SelfContained.lean is up to date",
    )
    args = parser.parse_args()

    rendered, ordered, external = render()
    digest = hashlib.sha256(rendered.encode("utf-8")).hexdigest()
    line_count = len(rendered.splitlines())

    if args.check:
        if not OUTPUT.exists() or normalized_text(OUTPUT) != rendered:
            print(f"out of date: {OUTPUT}", file=sys.stderr)
            return 1
        action = "checked"
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        with OUTPUT.open("w", encoding="utf-8", newline="\n") as stream:
            stream.write(rendered)
        action = "generated"

    print(
        f"{action} {OUTPUT.name}: "
        f"{len(ordered)} source modules, {len(external)} external imports, "
        f"{line_count} lines, sha256={digest}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
