import Erdos625.IndependentSets
import Erdos625.BoundedDifferences
import Erdos625.BlockBoundedDifferences
import Erdos625.RareSeedInversion
import Erdos625.VertexBlockGraph
import Erdos625.VertexBlockExpectation
import Erdos625.InducedCochromaticCapacity
import Erdos625.CochromaticAmplification
import Erdos625.CochromaticSeedGap
import Erdos625.CochromaticCapacityLowerTail
import Erdos625.PhaseExpansion
import Erdos625.PhaseEstimates
import Erdos625.PhaseAsymptotic
import Erdos625.PhaseConsequences
import Erdos625.ProfileEntropyS4
import Erdos625.ProfileOptimizerS4
import Erdos625.ProfileValueStabilityS4
import Erdos625.ProfileValueUniformS4
import Erdos625.ProfileOptimizerContinuityS4
import Erdos625.ProfileOptimizerUniformS4
import Erdos625.ColoringProfileFirstMoment
import Erdos625.ColoringProfileEnumeration
import Erdos625.ColoringProfileEnumerationInverse
import Erdos625.ColoringProfileEnumerationInjective
import Erdos625.ColoringProfileAggregation
import Erdos625.ProbabilityTools

/-!
# Kernel dependency audit

Compiling this module asks Lean to print the axioms used by representative
public theorems through the current verified bricks. Classical choice,
propositional extensionality, and quotient
soundness may legitimately enter through mathlib and finite minimization;
No placeholder axiom or project-defined axiom may appear.
-/

#print axioms Erdos625.coColorable_of_induce_and_compl
#print axioms Erdos625.coColorable_of_induce_and_colorable_compl
#print axioms Erdos625.coColorable_iff_cochromaticNumber_le
#print axioms Erdos625.cochromaticNumber_le_chromaticNumber
#print axioms Erdos625.gapConstant_pos
#print axioms Erdos625.randomGraphMeasure_singleton
#print axioms Erdos625.randomGraphMeasure_singleton_uniform
#print axioms Erdos625.measurableSet_gapEvent
#print axioms Erdos625.gapProbability_le_one
#print axioms Erdos625.erdos625Statement_iff_real
#print axioms Erdos625.phaseDelta_mem_Ico
#print axioms Erdos625.mu_succ_div_identity
#print axioms Erdos625.mu_pred_div_identity
#print axioms Erdos625.markov_measureReal_le
#print axioms Erdos625.paleyZygmund_zero
#print axioms Erdos625.mcdiarmid_two_sided_of_subgaussian
#print axioms Erdos625.binomialHalf_lowerQuarter_le_exp
#print axioms Erdos625.randomGraphMeasure_independentEvent
#print axioms Erdos625.independentSetExpectation_eq_ofReal_mu
#print axioms Erdos625.independenceNumberExceedsEvent_eq_countPositive
#print axioms Erdos625.randomGraphMeasure_independenceNumberExceeds_le_mu_succ
#print axioms Erdos625.alphaZero_eq_two_phaseS_div_q_add_one
#print axioms Erdos625.exists_phaseK_abs_bound
#print axioms Erdos625.eventually_phaseRangeDomain
#print axioms Erdos625.phaseNat_isEquivalent_scaled_logOrder
#print axioms Erdos625.eventually_two_mul_phaseNat_le
#print axioms Erdos625.log_descFactorial_linear_error_le
#print axioms Erdos625.stirlingLogRemainder_mem_Icc
#print axioms Erdos625.log_mu_sub_phaseStirlingMain_abs_le
#print axioms Erdos625.phaseBracket_sub_main_abs_le
#print axioms Erdos625.phaseBracket_sub_main_isBigO
#print axioms Erdos625.phaseStirlingResidual_isBigO_inv_logOrder
#print axioms Erdos625.phaseMain_algebra_identity
#print axioms Erdos625.phaseExpansionResidual_isBigO
#print axioms Erdos625.log_mu_phaseNat_add_two_div_logOrder_sub_phaseDelta_add_two_tendsto_zero
#print axioms Erdos625.mu_phaseNat_add_two_tendsto_zero
#print axioms Erdos625.exists_pos_eventually_mu_phaseNat_sub_two_lower_bound
#print axioms Erdos625.randomGraphMeasure_independenceNumberExceeds_phaseNat_add_one_tendsto_zero
#print axioms Erdos625.cubeMean_exp_center_le
#print axioms Erdos625.integral_boolCubePMF_eq_cubeMean
#print axioms Erdos625.boundedDifferences_hasSubgaussianMGF
#print axioms Erdos625.boundedDifferences_twoSidedTail
#print axioms Erdos625.blockMean_succ
#print axioms Erdos625.integral_blockUniformPMF_eq_blockMean
#print axioms Erdos625.blockMean_exp_center_le
#print axioms Erdos625.blockBoundedDifferences_hasSubgaussianMGF
#print axioms Erdos625.blockBoundedDifferences_twoSidedTail
#print axioms Erdos625.blockBoundedDifferences_hasSubgaussianMGF_zero
#print axioms Erdos625.gap_le_sqrt_two_mul_of_exp_neg_le_exp_neg_sq_div
#print axioms Erdos625.integral_le_const_of_ae_le
#print axioms Erdos625.measureReal_levelSet_le_centeredUpperTail
#print axioms Erdos625.rareSeed_gap_le
#print axioms Erdos625.rareSeed_gap_le_of_hasSubgaussianMGF
#print axioms Erdos625.vertexBlocksEquiv
#print axioms Erdos625.card_vertexBlocks
#print axioms Erdos625.map_vertexBlockMeasure_eq_randomGraphMeasure
#print axioms Erdos625.blocksToGraph_induce_away_eq
#print axioms Erdos625.randomGraph_vertexBlock_twoSidedTail
#print axioms Erdos625.integral_randomGraphMeasure_eq_randomGraphBlockExpectation
#print axioms Erdos625.CoColoring.pullback
#print axioms Erdos625.cochromaticInducedCapacity_eq_card_iff
#print axioms Erdos625.cochromaticInducedCapacity_le_add_one_of_induce_away_eq
#print axioms Erdos625.cochromaticInducedCapacity_hasBlockOscillation
#print axioms Erdos625.blockVariance_noninitialUnitOscillation
#print axioms Erdos625.randomGraph_cochromaticInducedCapacity_upperTail
#print axioms Erdos625.randomGraph_cochromaticInducedCapacity_twoSidedTail
#print axioms Erdos625.exists_cochromaticInducedCapacity_witness
#print axioms Erdos625.capacity_witness_compl_card
#print axioms Erdos625.cochromaticNumber_le_add_chromaticNumber_compl
#print axioms Erdos625.exists_capacity_witness_with_compl_bound
#print axioms Erdos625.measurable_cochromaticInducedCapacity_real
#print axioms Erdos625.integrable_cochromaticInducedCapacity_real
#print axioms Erdos625.cochromaticInducedCapacity_levelSet_eq
#print axioms Erdos625.cochromaticVarianceProxy_pos
#print axioms Erdos625.cochromaticSeedGap_le
#print axioms Erdos625.cochromaticSeedGap_le_simplified
#print axioms Erdos625.randomGraph_cochromaticInducedCapacity_lowerTail
#print axioms Erdos625.randomGraph_cochromaticInducedCapacity_failureProbability_le
#print axioms Erdos625.randomGraph_cochromaticInducedCapacity_strictFailureProbability_le
#print axioms Erdos625.ProfileEntropyS4.sum_weight
#print axioms Erdos625.ProfileEntropyS4.hasDerivAt_mean
#print axioms Erdos625.ProfileEntropyS4.variance_pos
#print axioms Erdos625.ProfileEntropyS4.strictMono_mean
#print axioms Erdos625.ProfileEntropyS4.tendsto_mean_atBot
#print axioms Erdos625.ProfileEntropyS4.tendsto_mean_atTop
#print axioms Erdos625.ProfileEntropyS4.existsUnique_mean_eq_of_mem_Ioo
#print axioms Erdos625.ProfileEntropyS4.mean_tilt_eq
#print axioms Erdos625.ProfileEntropyS4.optimizer_isFeasible
#print axioms Erdos625.ProfileEntropyS4.entropy_score_le_log_partition_sub_tilt_mul_target
#print axioms Erdos625.ProfileEntropyS4.optimizer_entropy_score_eq_log_partition_sub_tilt_mul_target
#print axioms Erdos625.ProfileEntropyS4.sum_mul_sub_sum_mul_le
#print axioms Erdos625.ProfileEntropyS4.abs_optimizedValue_sub_optimizedValue_le
#print axioms Erdos625.ProfileEntropyS4.tendsto_optimizedValue_of_uniform_scores
#print axioms Erdos625.ProfileEntropyS4.eventually_uniformOn_optimizedValue_of_uniform_scores
#print axioms Erdos625.ProfileEntropyS4.eventually_uniform_optimizedValue_on_Ioo_of_uniform_scores
#print axioms Erdos625.ProfileEntropyS4.tendsto_mean_of_scores_and_parameter
#print axioms Erdos625.ProfileEntropyS4.tendsto_tilt_of_scores_and_target
#print axioms Erdos625.ProfileEntropyS4.tendsto_optimizer_of_scores_and_target
#print axioms Erdos625.ProfileEntropyS4.eventually_uniformOn_tilt_of_uniform_scores
#print axioms Erdos625.ProfileEntropyS4.eventually_uniformOn_optimizer_of_uniform_scores
#print axioms Erdos625.ProfileEntropyS4.exists_uniform_optimizer_lower_bound_on_compact
#print axioms Erdos625.ProfileEntropyS4.eventually_uniform_optimizer_pos_on_compact
#print axioms Erdos625.ColoringProfile.prod_factorial_count_sizes
#print axioms Erdos625.ColoringProfile.enumerativeCoefficient_mul_coordinateDenominator_eq
#print axioms Erdos625.ProfilePartition.ncard_partitionInternalGraph
#print axioms Erdos625.randomGraphMeasure_partitionColoringEvent
#print axioms Erdos625.profileColoringExpectation_eq_card_mul
#print axioms Erdos625.profileColoringExpectation_eq_formula_of_mass
#print axioms Erdos625.profileColoringExpectation_eq_zero_of_vertexMass_ne
#print axioms Erdos625.card_shapeSlot
#print axioms Erdos625.card_profileDecoration
#print axioms Erdos625.decoratedProfileInv_map
#print axioms Erdos625.shapeBlockIndexEquivKernelParts
#print axioms Erdos625.card_slotBlockPart
#print axioms Erdos625.partitionShape_slotKernelPartition
#print axioms Erdos625.profileEnumerationStatement_of_decorationBijection
#print axioms Erdos625.decoratedProfileEquiv_slotProfileDecoration
#print axioms Erdos625.slotKernelPartition_decoratedProfileEquiv
#print axioms Erdos625.profileDecoration_eq_of_equiv_eq
#print axioms Erdos625.totalProfileDecorationMap_injective
#print axioms Erdos625.totalProfileDecorationMap_surjective
#print axioms Erdos625.totalProfileDecorationEquiv
#print axioms Erdos625.profileDecorationBijectionStatement
#print axioms Erdos625.profileEnumerationStatement
#print axioms Erdos625.profileColoringExpectation_eq_formula
#print axioms Erdos625.ColoringProfile.coordinate_le_vertexMass
#print axioms Erdos625.mem_coloringProfileBox_of_vertexMass_eq
#print axioms Erdos625.card_coloringProfileBox
#print axioms Erdos625.mem_boundedColoringProfiles
#print axioms Erdos625.card_boundedColoringProfiles_le
#print axioms Erdos625.boundedProfileColoringExpectation_eq_sum
